[project]
name = "file-comp-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datacompy>=0.17.0",
    "pandas>=2.3.0",
    "polars>=1.31.0",
]
